#Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when 
increasing is False, the i-th output column is the input vector raised element-wise to the power 
of N - i - 1.

In [6]:
import numpy as np

In [14]:
# when increasing is False
vector = np.array([1, 2, 3, 5,6])
n = 5
matrix_des=np.matrix([x**(n-i-1) for x in vector for i in range(n)]).reshape(vector.size,n)
print(matrix_des)

[[   1    1    1    1    1]
 [  16    8    4    2    1]
 [  81   27    9    3    1]
 [ 625  125   25    5    1]
 [1296  216   36    6    1]]


In [15]:
# when increasing is True
vector = np.array([1, 2, 3, 5,6])
n = 5
matrix_ase=np.matrix([x**i for x in vector for i in range(n)]).reshape(vector.size,n)
print(matrix_ase)

[[   1    1    1    1    1]
 [   1    2    4    8   16]
 [   1    3    9   27   81]
 [   1    5   25  125  625]
 [   1    6   36  216 1296]]


 Question: Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [48]:
x=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3
h=1
def movingAvg(x, k):
    Avg_out=np.convolve(x, np.ones(k)/k, mode='valid')
    for i in Avg_out:
        print("y{0}={1:.3f}".format(h,i))
        


In [49]:
movingAvg(x, k) 

y1=5.000
y1=4.667
y1=5.667
y1=6.667
y1=9.667
y1=28.667
y1=49.333
y1=72.667
y1=84.000
y1=93.333
y1=116.333
